{
	"m1"				:{"auth":1,"cn":"超级用户",			"lnk":"#/privilege"},	
	"m2"				:{"auth":1,"cn":"导游审核认证",		"lnk":"#/verify"},
	"m3"				:{"auth":1,"cn":"景点",				"lnk":"#/attractions"},
	"m4"				:{"auth":1,"cn":"住宿",				"lnk":"#/lodge"},
	"m5"				:{"auth":1,"cn":"美食",				"lnk":"#/food"},
	"m6"				:{"auth":1,"cn":"其它",				"lnk":"#/other"},
	"m7"				:{"auth":1,"cn":"经典方案订单",		"lnk":"#/orders?type=classic"},
	"m8"				:{"auth":1,"cn":"特色方案订单",		"lnk":"#/orders?type=special"},
	"m9"				:{"auth":1,"cn":"带车陪游服务订单",	"lnk":"#/orders?type=withcar"},
	"m10"				:{ "auth":1,"cn":"免车陪游服务订单",	"lnk":"#/orders?type=withoutcar"},
	"m11"				:{ "auth":1,"cn":"带车接机服务订单",	"lnk":"#/orders?type=pickwithcar"},
	"m12"				:{ "auth":1,"cn":"带车送机服务订单",	"lnk":"#/orders?type=dropwithcar"},
	"m13"				:{ "auth":1,"cn":"其它服务订单 ",	"lnk":"#/orders?type=other"},
	"m14"				:{ "auth":1,"cn":"退款",				"lnk":"#/refund"},
	"m15"				:{ "auth":1,"cn":"提现",				"lnk":"#/cashout"},
	"m16"				:{ "auth":1,"cn":"经典方案",			"lnk":"#/plans?type=classic"},
	"m17"				:{ "auth":1,"cn":"特色方案",			"lnk":"#/plans?type=special"},
	"m18"				:{ "auth":1,"cn":"带车陪游服务",		"lnk":"#/services?type=withcar"},
	"m19"				:{ "auth":1,"cn":"免车陪游服务",		"lnk":"#/services?type=withoutcar"},
	"m20"				:{ "auth":1,"cn":"带车接机服务",		"lnk":"#/services?type=pickwithcar"},
	"m21"				:{ "auth":1,"cn":"带车送机服务",		"lnk":"#/services?type=dropwithcar"},
	"m22"				:{ "auth":1,"cn":"其它服务",			"lnk":"#/services?type=other"},
	"m23"				:{ "auth":1,"cn":"国家城市维护",		"lnk":"#/geograph"},
	"m24"				:{ "auth":1,"cn":"添加删除城市",		"lnk":"#/citymgr"}
}